const items =  {
    products: [
        {
            name: 'Blue Printed Denim Jacket',
            slug: 'blue-printed-denim-jacket',
            gender: 'men',
            color: 'blue',
            category: 'jackets',
            image: '/images/232358M177005_1.webp',
            price: 775,
            detail: ['Paneled construction','Spread collar','Button closure','Flap pockets and welt pockets',' Single-button barrel cuffs','Adjustable button tabs at back hem','Logo-engraved silver-tone hardware','Contrast stitching in tan'],
            countInStock: 10,
            designer: 'DRIES VAN NOTEN',
            rating: 4.6,
            numReviews: 10,
            description: 'Non-stretch denim jacket. Graphic pattern printed throughout.',
        },
        {
            name: 'White Heart Patch Polo',
            slug: 'white-heart-patch-polo',
            category: 'shirts',
            gender: 'men',
            image: '/images/232246M212000_1.webp',
            price: 60,
            countInStock: 8,
            designer: 'COMME DES GARÇONS PLAY',
            rating: 4.9,
            numReviews: 4,
            description: 'Cotton piqué polo.',
        },
        {
            name: 'Gray Double Waistband Jeans',
            slug: 'gray-double-waistband-jeans',
            category: 'jeans',
            gender: 'men',
            image: '/images/231477M186010_1.webp',
            price: 30,
            countInStock: 23,
            designer: 'JW ANDERSON',
            rating: 4.2,
            numReviews: 15,
            description: 'Non-stretch denim jeans. Fading throughout',
        },
        {
            name: 'Black Striped Trousers',
            slug: 'black-striped-trousers',
            category: 'trousers',
            gender: 'men',
            image: '/images/231705M191001_1.webp',
            price: 40,
            countInStock: 12,
            designer: 'ATTACHMENT',
            rating: 4.6,
            numReviews: 13,
            description: 'Plain-woven cotton-blend trousers. Stripes and laddering throughout.',
        },
        {
            name: 'Black Medium Signature Camera Bag',
            slug: 'black-medium-signature-camera-bag',
            category: 'bags',
            gender: 'men',
            image: '/images/232342M170008_1.webp',
            price: 1000,
            countInStock: 8,
            designer: 'BALENCIAGA',
            rating: 4.2,
            numReviews: 1,
            description: 'Coated canvas messenger bag in black. Logo pattern printed throughout.',
        },
        {
            name: 'Black & White Converse Edition PLAY Chuck 70 High Top Sneakers',
            slug: 'black-white-converse-edition-play-chuck-70-high-top-sneakers',
            category: 'shoes',
            gender: 'men',
            image: '/images/231246M236000_1.webp',
            price: 150,
            countInStock: 8,
            designer: 'COMME DES GARÇONS PLAY',
            rating: 4.0,
            numReviews: 3,
            description: 'High-top canvas sneakers in black and white.',
        },
        {
            name: `Off-White 'NY Tennis Club' Cap`,
            slug: 'off-white-ny-tennis-club-cap',
            category: 'accessories',
            gender: 'men',
            image: '/images/232446M139000_1.webp',
            price: 60,
            countInStock: 7,
            designer: 'SPORTY & RICH',
            rating: 3.6,
            numReviews: 0,
            description: 'Paneled cotton twill cap in off-white.',
        },
        {
            name: 'Black Mega Sunglasses',
            slug: 'black-mega-sunglasses',
            category: 'accessories',
            gender: 'men',
            image: '/images/232191M134068_1.webp',
            price: 225,
            countInStock: 2,
            designer: 'RETROSUPERFUTURE',
            rating: 3.6,
            numReviews: 0,
            description: 'Handcrafted square acetate-frame sunglasses in black.',
        },
        {
            name: 'Black Guinevere Maxi Dress',
            slug: 'black-guinevere-maxi-dress',
            category: 'dress',
            gender: 'women',
            image: '/images/232359F055009_1.webp',
            price: 4450,
            countInStock: 5,
            designer: 'THE ROW',
            rating: 4.6,
            numReviews: 10,
            description: 'Silk satin dress',
        },
        {
            name: 'Khaki 1996 Retro Nuptse Down Jacket',
            slug: 'khaki-1996-retro-nuptse-down-jacket',
            category: 'jacket',
            gender: 'women',
            image: '/images/232802F061029_1.webp',
            price: 340,
            countInStock: 15,
            designer: 'THE NORTH FACE',
            rating: 4.9,
            numReviews: 30,
            description: 'RDS-certified down-filled quilted non-PFC DWR-coated recycled nylon ripstop and taffeta jacket. Water-repellent.',
        },
        {
            name: 'Indigo Distressed Denim Shorts',
            slug: 'indigo-distressed-denim-shorts',
            category: 'shorts',
            gender: 'women',
            image: '/images/232923F088011_1.webp',
            price: 630,
            countInStock: 5,
            designer: 'RHUDE',
            rating: 4.3,
            numReviews: 10,
            description: 'Non-stretch denim shorts. Distressing, fading, and paint splatter effect throughout.',
        },
        {
            name: 'Blue Relaxed-Fit Sweatshirt',
            slug: 'blue-relaxed-fit-sweatshirt',
            category: 'sweaters',
            gender: 'women',
            image: '/images/232129F098003_1.webp',
            price: 350,
            countInStock: 2,
            designer: 'ACNE STUDIOS',
            rating: 4.3,
            numReviews: 2,
            description: 'Organic cotton fleece sweatshirt.',
        },
        {
            name: 'Beige Small Cabata Tote',
            slug: 'beige-small-cabata-tote',
            category: 'bags',
            gender: 'women',
            image: '/images/christian-louboutin-beige-small-cabata-tote.jpg',
            price: 1390,
            countInStock: 6,
            designer: 'CHRISTIAN LOUBOUTIN',
            rating: 4.5,
            numReviews: 2,
            description: 'Grained calfskin tote in beige. Studs throughout.',
        },
        {
            name:`Taupe 'The Stockholm' Beanie`,
            slug: 'taupe-the-stockholm-beanie',
            category: 'accessories',
            gender: 'women',
            image: '/images/232581F014004_1.webp',
            price: 165,
            countInStock: 2,
            designer: 'LISA YANG',
            rating: 3.9,
            numReviews: 4,
            description: '7-gauge rib knit cashmere beanie in taupe. Rolled brim.',
        },
        {
            name:'Purple Julie Heeled Sandals',
            slug: 'purple-julie-heeled-sandals',
            category: 'shoes',
            gender: 'women',
            image: '/images/232187F125022_1.webp',
            price: 165,
            countInStock: 6,
            designer: 'LISA YANG',
            rating: 3.9,
            numReviews: 4,
            description: 'Padded webbing heeled sandals in purple.',
        },
        {
            name:`Red Le Chouchou 'Le Petit Bambimou Nylon' Bag`,
            slug: 'red-le-chouchou-le-petit-bambimou-nylon-bag',
            category: 'bags',
            gender: 'women',
            image: '/images/232553F048015_1.webp',
            price: 920,
            countInStock: 20,
            designer: 'JACQUEMUS',
            rating: 3.0,
            numReviews: 1,
            description: 'Padded nylon twill messenger bag in red. Buffed leather trim throughout.'
        },
        {
            name: 'Yellow Cantine Small Plate Set, 4pcs',
            slug: 'yellow-cantine-small-plate-set-4pcs',
            gender: 'none',
            category: 'tablewares',
            image: '/images/231231M798047_1.webp',
            price: 105,
            countInStock: 3,
            designer: 'JARS CERAMISTES',
            rating: 4.7,
            numReviews: 2,
            description: 'Set of four handcrafted glazed ceramic plates in yellow.',
        },
        {
            name: 'SSENSE Exclusive Green Small Blot Rug',
            slug: 'ssense-exclusive-green-small-blot-rug',
            gender: 'none',
            category: 'furnitures',
            image: '/images/mush-studios-ssense-exclusive-green-small-blot-rug.jpg',
            price: 105,
            countInStock: 3,
            designer: 'JARS CERAMISTES',
            rating: 4.7,
            numReviews: 2,
            description: 'Set of four handcrafted glazed ceramic plates in yellow.',
        },
        {
            name: `Black 'The Puffer' iPhone 14 Pro Case`,
            slug: 'black-the-puffer-iphone14-pro-case',
            gender: 'none',
            category: 'accessories',
            image: '/images/222565M645009_1.webp',
            price: 65,
            countInStock: 4,
            designer: 'THE PUFFER CASE',
            rating: 4.7,
            numReviews: 2,
            description: 'Quilted phone case in black. Logo embossed at face.',
        },
        {
            name: 'Pink Panton Chair',
            slug: 'pink-panton-chair',
            gender: 'none',
            category: 'accessories',
            image: '/images/231059M809008_1.webp',
            price: 65,
            countInStock: 4,
            designer: 'VITRA',
            rating: 3.7,
            numReviews: 3,
            description: 'Dyed-through polypropylene chair in pink. Single-piece injection-molded construction..',
        },
    ],
    
}

export default items;